### ISSUE TITLE
Example page is broken

### ISSUE THREAD

**Issue by asbachb** [tailwindtoolbox/Admin-Template-Day#4]
https://tailwindtoolbox.github.io/Admin-Template-Day/ is broken

seems that tailwind css cannot be resolved: https://unpkg.com/tailwindcss@next/dist/tailwind.min.css

```
The resource from “https://unpkg.com/tailwindcss@next/dist/tailwind.min.css” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
```

**Comment by tailwindtoolbox** [comment]
Thanks @asbachb  - fixed now... looks like the @next link isn't working anymore!
